server:
  port: 9001

spring:
  cloud:
    gateway:
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE:8001
          predicates:
            - Path=/user/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://ms-dis-service:8761/eureka/"